### ISSUE TITLE
leanote nodb版本镜像启动失败报错 router initialize error

### ISSUE THREAD

**Issue by wwwvmware** [zengchw/leanote#17]
### 重现方式

```shell
leanote_test >  mkdir conf files upload

leanote_test >   cat docker-compose.yaml
version: "3"
services:
  nginx:
    container_name: leanote_test
    image: axboy/leanote:nodb
    restart: always
    ports:
        - 12348:9000
    volumes:
       - ./conf/:/data/leanote/conf
       - ./files:/data/leanote/files
       - ./upload:/data/leanote/public/upload


 leanote_test >  docker-compose up 
```
### 报错
```shell
leanote_test | DEBUG 22:25:17  revel server.go:106: InitServerEngine: Found server engine and invoking  section=server name=go
leanote_test | panic: init: router initialize error
leanote_test |
leanote_test | goroutine 1 [running]:
leanote_test | github.com/leanote/leanote/vendor/github.com/revel/revel/logger.(*RevelLogger).Panic(0xc420040ec0, 0xb5a473, 0x1d, 0xc4203736e0, 0x2, 0x2)
leanote_test |  /Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/vendor/github.com/revel/revel/logger/logger.go:149 +0xaf
leanote_test | github.com/leanote/leanote/vendor/github.com/revel/revel.init.5.func1()
leanote_test |  /Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/vendor/github.com/revel/revel/router.go:840 +0x241
leanote_test | github.com/leanote/leanote/vendor/github.com/revel/revel.runStartupHooks()
leanote_test |  /Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/vendor/github.com/revel/revel/server.go:126 +0x7f
leanote_test | github.com/leanote/leanote/vendor/github.com/revel/revel.InitServer()
leanote_test |  /Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/vendor/github.com/revel/revel/server.go:37 +0x39
leanote_test | github.com/leanote/leanote/vendor/github.com/revel/revel.Run(0x0)
leanote_test |  /Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/vendor/github.com/revel/revel/server.go:69 +0xd4
leanote_test | main.main()
leanote_test |  /Users/life/Documents/Go/package_base/src/github.com/leanote/leanote/app/tmp/main.go:2312 +0x223d5

```
### 期待修复的效果  
容器正常启动

### 环境版本说明

操作系统
```shell 
leanote_test >  uname -a
Linux 192.168.5.4 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
docker 版本
```shell
 leanote_test >  docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:35:25 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:34:28 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
docker-compose 版本
```shell
 leanote_test >  docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Comment by wwwvmware** [comment]
与大佬@axboy 求助后得到解决方案，使用latest镜像挂载 conf,files,upload三个目录后停止容器，再重新启动nodb版本可以正常启动了。
